parameters:
    openium_platinium.server_url: 'https://platinium.openium.fr'
    openium_platinium.notify_path: '/api/server/notify.json'
    openium_platinium.subscribed_path: '/api/server/subscribed.json'
    openium_platinium.server.id: '%env(resolve:PLATINIUM_SERVER_ID)%'
    openium_platinium.server.key: '%env(resolve:PLATINIUM_SERVER_KEY)%'
    openium_platinium.token.dev: '%env(resolve:PLATINIUM_SERVER_TOKEN_DEV)%'
    openium_platinium.token.prod: '%env(resolve:PLATINIUM_SERVER_TOKEN_PROD)%'

services:
    openium_platinium.signature_service:
        class: Openium\PlatiniumBundle\Service\PlatiniumSignatureService
        autowire: false
        arguments:
            - '%openium_platinium.server.id%'
            - '%openium_platinium.server.key%'
        public: false

    openium_platinium.parameter_bag_service:
        class: Openium\PlatiniumBundle\Service\PlatiniumParameterBagService
        autowire: false
        arguments:
            - '%kernel.environment%'
            - '%openium_platinium.token.dev%'
            - '%openium_platinium.token.prod%'
        public: false

    openium_platinium.client:
        class: Openium\PlatiniumBundle\PlatiniumClient
        autowire: false
        arguments:
            - '%openium_platinium.server_url%'
            - '@openium_platinium.signature_service'
            - '%kernel.environment%'
        public: false

    openium_platinium.notifier:
        class: Openium\PlatiniumBundle\PlatiniumNotifier
        autowire: false
        arguments:
            - '@openium_platinium.client'
            - '@openium_platinium.parameter_bag_service'
            - '%openium_platinium.notify_path%'
            - '%openium_platinium.subscribed_path%'
        public: true
